name: E2E Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start local server
        run: |
          npx http-server -p 3000 &
          npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --spec "cypress/e2e/counter.spec.cy.ts"

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: cypress/screenshots