name: E2E Tests
on: [push]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
        - name: Cypress.io
          uses: cypress-io/github-action@v6.5.0
          with:
            start: npx http-server -p 3000
        - name: Upload Cypress screenshots
          if: failure()
          uses: actions/upload-artifact@v4
          with:
              name: cypress-screenshots
              path: cypress/screenshots
        - name: Upload E2E Test Report
          if: always()
          uses: actions/upload-artifact@v4
          with:
              name: E2E Tests
              path: cypress/reports    
